# Site settings
title: McNeel Product Documentation
# email: brian@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.mcneel.com" # the base hostname & protocol for your site
editMeOnGhBaseUrl: "mcneel/help-docs"

# To Generate a local Sitemap, remove the following 2 comments on the lines. And set safe: below to false.
#gems:
#  - jekyll-sitemap


# twitter_username: ""
github_username:  mcneel
simple_search: http://google.com/search
# Build settings
#markdown: redcarpet
encoding: utf-8

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM

#port: 4444

safe: safe


collections:
  - faqs
  - guides_topics
  - help
  - tutorials
  - en-flamingo
  - kr-website
  - kr-help
  - kr-guide_topics

collections:
  website:
    output: true
    permalink: /en/flamingo/5/website/:path/
  help:
    output: true
    permalink: /en/flamingo/5/help/:path/
  guides_topics:
    output: true
    permalink: /en/flamingo/5/guides/:path/
  kr-website:
    output: true
    permalink: /kr/flamingo/5/website/:path/
  kr-help:
    output: true
    permalink: /kr/flamingo/5/help/:path/
  kr-guides_topics:
    output: true
    permalink: /kr/flamingo/5/guides/:path/ 
defaults:
  -
    scope:
      path: "en/flamingo"
    values:
      language: en
      productname: "Flamingo NXT Documentation"
      productpath: flamingo
      productversionpath: "5"
  -
    scope:
      path: "en/flamingo/5/help"
    values:
      category: "help"
      layout: flamingo-toc-page
      collectionname: "Help"
  -
    scope:
      path: "en/flamingo/5/guides"
    values:
      type: "guides_topic"
      layout: flamingo-toc-page
      collectionname: "Guides"
      sort: 1
  -
    scope:
      path: "kr/flamingo"
    values:
      language: kr
      productname: "Flamingo NXT 문서"
      productpath: flamingo
      productversionpath: "5"
  -
    scope:
      path: "kr/flamingo/5/help"
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "도움말"
  -
    scope:
      path: "kr/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-toc-page
      collectionname: "가이드"

